// <auto-generated />
namespace HC_Pharma.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class partner1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(partner1));
        
        string IMigrationMetadata.Id
        {
            get { return "202212220910060_partner1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
